* 没有找到任何`catch`的exception对象将会被`terminate`函数捕获
* 出现异常时，对象可能处于无效或不完整的状态，资源可能没有被释放，在发生异常时做适当的资源清理，这称为`异常安全`
